package com.brothersfight.bjjchecklist.model

val ALL_REQUIREMENTS: List<Requirement> = listOf(
    // ──────────── FAIXA AZUL ────────────
    // Quedas
    Requirement("azul-quedas-1", "azul", "Quedas", "Double Leg"),
    Requirement("azul-quedas-2", "azul", "Quedas", "Single Leg"),
    // Passagem
    Requirement("azul-passagem-1", "azul", "Passagem", "Passagem guarda fechada"),
    Requirement("azul-passagem-2", "azul", "Passagem", "Passada de meia guarda com joelho espetado"),
    Requirement("azul-passagem-3", "azul", "Passagem", "Passagem de meia guarda para montada"),
    Requirement("azul-passagem-4", "azul", "Passagem", "Passagem de guarda aberta toreador"),
    // Cem Kilos
    Requirement("azul-cemkilos-1", "azul", "Cem Kilos", "Americana"),
    Requirement("azul-cemkilos-2", "azul", "Cem Kilos", "Katagatame"),
    Requirement("azul-cemkilos-3", "azul", "Cem Kilos", "Kimura"),
    Requirement("azul-cemkilos-4", "azul", "Cem Kilos", "Kimura norte sul"),
    Requirement("azul-cemkilos-5", "azul", "Cem Kilos", "Arm lock"),
    // Joelho na Barriga
    Requirement("azul-joelho-1", "azul", "Joelho na Barriga", "Arm lock"),
    Requirement("azul-joelho-2", "azul", "Joelho na Barriga", "Estrangulamento cruzado"),
    Requirement("azul-joelho-3", "azul", "Joelho na Barriga", "Estrangulamento cruzado com lapela"),
    // Montada
    Requirement("azul-montada-1", "azul", "Montada", "Americana"),
    Requirement("azul-montada-2", "azul", "Montada", "Ezequiel"),
    Requirement("azul-montada-3", "azul", "Montada", "Arm lock"),
    Requirement("azul-montada-4", "azul", "Montada", "Estrangulamento Cruzado"),
    // Guarda Fechada
    Requirement("azul-guarda-1", "azul", "Guarda Fechada", "Arm lock"),
    Requirement("azul-guarda-2", "azul", "Guarda Fechada", "Omoplata"),
    Requirement("azul-guarda-3", "azul", "Guarda Fechada", "Triangulo"),
    Requirement("azul-guarda-4", "azul", "Guarda Fechada", "Kimura"),
    Requirement("azul-guarda-5", "azul", "Guarda Fechada", "Estrangulamento Cruzado"),
    // Meia Guarda
    Requirement("azul-meia-1", "azul", "Meia Guarda", "Raspagem com esgrima"),
    Requirement("azul-meia-2", "azul", "Meia Guarda", "Raspagem esgrima com pegada de costa"),
    // Costas
    Requirement("azul-costas-1", "azul", "Costas", "Mata-Leão"),
    Requirement("azul-costas-2", "azul", "Costas", "Estrangulamento Cruzado"),
    Requirement("azul-costas-3", "azul", "Costas", "Arco e Flexa"),
    // Raspagem
    Requirement("azul-raspagem-1", "azul", "Raspagem", "Raspagem da guarda fechada pra montada"),
    Requirement("azul-raspagem-2", "azul", "Raspagem", "Raspagem tesoura"),
    Requirement("azul-raspagem-3", "azul", "Raspagem", "Raspagem Kimura"),
    Requirement("azul-raspagem-4", "azul", "Raspagem", "Raspagem de gancho"),
    // Saídas
    Requirement("azul-saidas-1", "azul", "Saídas", "Saída da Montada"),
    Requirement("azul-saidas-2", "azul", "Saídas", "Saída dos 100 Kilos"),
    Requirement("azul-saidas-3", "azul", "Saídas", "Saída das Costas"),
    Requirement("azul-saidas-4", "azul", "Saídas", "Saída do Triangulo"),
    Requirement("azul-saidas-5", "azul", "Saídas", "Saída do Arm Lock da guarda fechada"),
    Requirement("azul-saidas-6", "azul", "Saídas", "Saída do Arm Lock com as costas no chão"),
    Requirement("azul-saidas-7", "azul", "Saídas", "Reposição de guarda fechada"),
    // Fundamentos
    Requirement("azul-fund-1", "azul", "Fundamentos", "Amarrar Faixa"),
    Requirement("azul-fund-2", "azul", "Fundamentos", "Pontuações"),
    Requirement("azul-fund-3", "azul", "Fundamentos", "Saída de quadril"),
    Requirement("azul-fund-4", "azul", "Fundamentos", "Rolamento de frente"),
    Requirement("azul-fund-5", "azul", "Fundamentos", "Rolamento de costas"),
    Requirement("azul-fund-6", "azul", "Fundamentos", "Sprawl"),
    Requirement("azul-fund-7", "azul", "Fundamentos", "Chamar na guarda fechada"),
    Requirement("azul-fund-8", "azul", "Fundamentos", "Chamar na guarda aberta"),
    Requirement("azul-fund-9", "azul", "Fundamentos", "Chamar na meia guarda"),
    // Ataque de Pé
    Requirement("azul-ataque-1", "azul", "Ataque de Pé", "Botinha na passagem de guarda"),

    // ──────────── FAIXA ROXA ────────────
    Requirement("roxa-baianas-1", "roxa", "Baianas", "Baiana leve"),
    Requirement("roxa-baianas-2", "roxa", "Baianas", "Baiana pesado"),
    Requirement("roxa-quedas-1", "roxa", "Quedas", "Queda 1"),
    Requirement("roxa-quedas-2", "roxa", "Quedas", "Queda 2"),
    Requirement("roxa-quedas-3", "roxa", "Quedas", "Queda 3"),
    Requirement("roxa-quedas-4", "roxa", "Quedas", "Queda 4"),
    Requirement("roxa-quedas-5", "roxa", "Quedas", "Queda 5"),
    Requirement("roxa-quedas-6", "roxa", "Quedas", "Queda 6"),
    Requirement("roxa-rasp-joelhos-1", "roxa", "Raspagem", "Raspagem com oponente de joelhos 1"),
    Requirement("roxa-rasp-joelhos-2", "roxa", "Raspagem", "Raspagem com oponente de joelhos 2"),
    Requirement("roxa-rasp-pe-1", "roxa", "Raspagem", "Raspagem com oponente em pé 1"),
    Requirement("roxa-rasp-pe-2", "roxa", "Raspagem", "Raspagem com oponente em pé 2"),
    Requirement("roxa-rasp-meia-1", "roxa", "Raspagem", "Raspagem da meia guarda 1"),
    Requirement("roxa-rasp-meia-2", "roxa", "Raspagem", "Raspagem da meia guarda 2"),
    Requirement("roxa-passagens-1", "roxa", "Passagem", "Passagem de guarda 1"),
    Requirement("roxa-passagens-2", "roxa", "Passagem", "Passagem de guarda 2"),
    Requirement("roxa-passagens-3", "roxa", "Passagem", "Passagem de guarda 3"),
    Requirement("roxa-passagens-4", "roxa", "Passagem", "Passagem de guarda 4"),
    Requirement("roxa-armlocks-1", "roxa", "Finalizações", "Arm Lock 1"),
    Requirement("roxa-armlocks-2", "roxa", "Finalizações", "Arm Lock 2"),
    Requirement("roxa-armlocks-3", "roxa", "Finalizações", "Arm Lock 3"),
    Requirement("roxa-triangulos-1", "roxa", "Finalizações", "Triângulo 1"),
    Requirement("roxa-triangulos-2", "roxa", "Finalizações", "Triângulo 2"),
    Requirement("roxa-omoplatas-1", "roxa", "Finalizações", "Omoplata 1"),
    Requirement("roxa-omoplatas-2", "roxa", "Finalizações", "Omoplata 2"),
    Requirement("roxa-estrang-guarda-1", "roxa", "Finalizações", "Estrangulamento na guarda 1"),
    Requirement("roxa-estrang-guarda-2", "roxa", "Finalizações", "Estrangulamento na guarda 2"),
    Requirement("roxa-estrang-guarda-3", "roxa", "Finalizações", "Estrangulamento na guarda 3"),
    Requirement("roxa-estrang-montada-1", "roxa", "Finalizações", "Estrangulamento na montada 1"),
    Requirement("roxa-estrang-montada-2", "roxa", "Finalizações", "Estrangulamento na montada 2"),
    Requirement("roxa-estrang-montada-3", "roxa", "Finalizações", "Estrangulamento na montada 3"),
    Requirement("roxa-final-100kg-1", "roxa", "Finalizações", "Finalização no 100kg 1"),
    Requirement("roxa-final-100kg-2", "roxa", "Finalizações", "Finalização no 100kg 2"),
    Requirement("roxa-final-100kg-3", "roxa", "Finalizações", "Finalização no 100kg 3"),
    Requirement("roxa-saidas-montada-1", "roxa", "Saídas", "Saída da montada 1"),
    Requirement("roxa-saidas-montada-2", "roxa", "Saídas", "Saída da montada 2"),
    Requirement("roxa-saidas-costas-1", "roxa", "Saídas", "Saída de pegada pelas costas 1"),
    Requirement("roxa-saidas-costas-2", "roxa", "Saídas", "Saída de pegada pelas costas 2"),
    Requirement("roxa-costas-1", "roxa", "Costas", "Ida para as costas - Berimbolo"),
    Requirement("roxa-costas-2", "roxa", "Costas", "Ida para as costas 2"),

    // ──────────── FAIXA MARROM ────────────
    Requirement("marrom-baianas-1", "marrom", "Baianas", "Baiana leve"),
    Requirement("marrom-baianas-2", "marrom", "Baianas", "Baiana pesado"),
    Requirement("marrom-quedas-1", "marrom", "Quedas", "Queda 1"),
    Requirement("marrom-quedas-2", "marrom", "Quedas", "Queda 2"),
    Requirement("marrom-quedas-3", "marrom", "Quedas", "Queda 3"),
    Requirement("marrom-quedas-4", "marrom", "Quedas", "Queda 4"),
    Requirement("marrom-quedas-5", "marrom", "Quedas", "Queda 5"),
    Requirement("marrom-quedas-6", "marrom", "Quedas", "Queda 6"),
    Requirement("marrom-quedas-7", "marrom", "Quedas", "Queda 7"),
    Requirement("marrom-quedas-8", "marrom", "Quedas", "Queda 8"),
    Requirement("marrom-rasp-joelhos-1", "marrom", "Raspagem", "Raspagem com oponente de joelhos 1"),
    Requirement("marrom-rasp-joelhos-2", "marrom", "Raspagem", "Raspagem com oponente de joelhos 2"),
    Requirement("marrom-rasp-joelhos-3", "marrom", "Raspagem", "Raspagem com oponente de joelhos 3"),
    Requirement("marrom-rasp-pe-1", "marrom", "Raspagem", "Raspagem com oponente em pé 1"),
    Requirement("marrom-rasp-pe-2", "marrom", "Raspagem", "Raspagem com oponente em pé 2"),
    Requirement("marrom-rasp-pe-3", "marrom", "Raspagem", "Raspagem com oponente em pé 3"),
    Requirement("marrom-rasp-meia-1", "marrom", "Raspagem", "Raspagem da meia guarda 1"),
    Requirement("marrom-rasp-meia-2", "marrom", "Raspagem", "Raspagem da meia guarda 2"),
    Requirement("marrom-rasp-meia-3", "marrom", "Raspagem", "Raspagem da meia guarda 3"),
    Requirement("marrom-rasp-5050", "marrom", "Raspagem", "Raspagem da guarda 50/50"),
    Requirement("marrom-rasp-lapela", "marrom", "Raspagem", "Raspagem da guarda de lapela"),
    Requirement("marrom-passagens-1", "marrom", "Passagem", "Passagem de guarda 1"),
    Requirement("marrom-passagens-2", "marrom", "Passagem", "Passagem de guarda 2"),
    Requirement("marrom-passagens-3", "marrom", "Passagem", "Passagem de guarda 3"),
    Requirement("marrom-passagens-4", "marrom", "Passagem", "Passagem de guarda 4"),
    Requirement("marrom-passagens-5", "marrom", "Passagem", "Passagem da meia guarda"),
    Requirement("marrom-passagens-6", "marrom", "Passagem", "Passagem da guarda 50/50"),
    Requirement("marrom-passagens-7", "marrom", "Passagem", "Passagem da guarda de lapela"),
    Requirement("marrom-armlocks-1", "marrom", "Finalizações", "Arm Lock 1"),
    Requirement("marrom-armlocks-2", "marrom", "Finalizações", "Arm Lock 2"),
    Requirement("marrom-armlocks-3", "marrom", "Finalizações", "Arm Lock 3"),
    Requirement("marrom-armlocks-4", "marrom", "Finalizações", "Arm Lock 4"),
    Requirement("marrom-triangulos-1", "marrom", "Finalizações", "Triângulo 1"),
    Requirement("marrom-triangulos-2", "marrom", "Finalizações", "Triângulo 2"),
    Requirement("marrom-omoplatas-1", "marrom", "Finalizações", "Omoplata 1"),
    Requirement("marrom-omoplatas-2", "marrom", "Finalizações", "Omoplata 2"),
    Requirement("marrom-final-joelho-1", "marrom", "Finalizações", "Finalização com joelho na barriga 1"),
    Requirement("marrom-final-joelho-2", "marrom", "Finalizações", "Finalização com joelho na barriga 2"),
    Requirement("marrom-final-joelho-3", "marrom", "Finalizações", "Finalização com joelho na barriga 3"),
    Requirement("marrom-final-costas-1", "marrom", "Finalizações", "Finalização nas costas 1"),
    Requirement("marrom-final-costas-2", "marrom", "Finalizações", "Finalização nas costas 2"),
    Requirement("marrom-final-costas-3", "marrom", "Finalizações", "Finalização nas costas 3"),
    Requirement("marrom-final-costas-4", "marrom", "Finalizações", "Finalização nas costas 4"),
    Requirement("marrom-final-5050", "marrom", "Finalizações", "Finalização da guarda 50/50"),
    Requirement("marrom-final-pe-1", "marrom", "Finalizações", "Finalização no pé 1"),
    Requirement("marrom-final-pe-2", "marrom", "Finalizações", "Finalização no pé 2"),
    Requirement("marrom-final-pe-3", "marrom", "Finalizações", "Finalização no pé 3"),
    Requirement("marrom-leglock-1", "marrom", "Finalizações", "Leg Lock 1"),
    Requirement("marrom-leglock-2", "marrom", "Finalizações", "Leg Lock 2"),
    Requirement("marrom-estrang-100kg-1", "marrom", "Finalizações", "Estrangulamento no 100kg 1"),
    Requirement("marrom-estrang-100kg-2", "marrom", "Finalizações", "Estrangulamento no 100kg 2"),
    Requirement("marrom-estrang-100kg-3", "marrom", "Finalizações", "Estrangulamento no 100kg 3"),
    Requirement("marrom-saidas-1", "marrom", "Saídas", "Saída da montada 1"),
    Requirement("marrom-saidas-2", "marrom", "Saídas", "Saída da montada 2"),
    Requirement("marrom-saidas-3", "marrom", "Saídas", "Saída da montada 3"),
    Requirement("marrom-costas-1", "marrom", "Costas", "Ida para as costas - Berimbolo"),
    Requirement("marrom-costas-2", "marrom", "Costas", "Ida para as costas 2"),
    Requirement("marrom-costas-3", "marrom", "Costas", "Ida para as costas 3"),

    // ──────────── FAIXA PRETA ────────────
    Requirement("preta-baianas-1", "preta", "Baianas", "Baiana leve"),
    Requirement("preta-baianas-2", "preta", "Baianas", "Baiana pesado"),
    Requirement("preta-quedas-1", "preta", "Quedas", "Queda 1"),
    Requirement("preta-quedas-2", "preta", "Quedas", "Queda 2"),
    Requirement("preta-quedas-3", "preta", "Quedas", "Queda 3"),
    Requirement("preta-quedas-4", "preta", "Quedas", "Queda 4"),
    Requirement("preta-quedas-5", "preta", "Quedas", "Queda 5"),
    Requirement("preta-quedas-6", "preta", "Quedas", "Queda 6"),
    Requirement("preta-quedas-7", "preta", "Quedas", "Queda 7"),
    Requirement("preta-quedas-8", "preta", "Quedas", "Queda 8"),
    Requirement("preta-rasp-joelhos-1", "preta", "Raspagem", "Raspagem com oponente de joelhos 1"),
    Requirement("preta-rasp-joelhos-2", "preta", "Raspagem", "Raspagem com oponente de joelhos 2"),
    Requirement("preta-rasp-joelhos-3", "preta", "Raspagem", "Raspagem com oponente de joelhos 3"),
    Requirement("preta-rasp-pe-1", "preta", "Raspagem", "Raspagem com oponente em pé 1"),
    Requirement("preta-rasp-pe-2", "preta", "Raspagem", "Raspagem com oponente em pé 2"),
    Requirement("preta-rasp-pe-3", "preta", "Raspagem", "Raspagem com oponente em pé 3"),
    Requirement("preta-rasp-meia-1", "preta", "Raspagem", "Raspagem da meia guarda 1"),
    Requirement("preta-rasp-meia-2", "preta", "Raspagem", "Raspagem da meia guarda 2"),
    Requirement("preta-rasp-meia-3", "preta", "Raspagem", "Raspagem da meia guarda 3"),
    Requirement("preta-rasp-5050", "preta", "Raspagem", "Raspagem da guarda 50/50"),
    Requirement("preta-rasp-lapela", "preta", "Raspagem", "Raspagem da guarda de lapela"),
    Requirement("preta-passagens-1", "preta", "Passagem", "Passagem de guarda 1"),
    Requirement("preta-passagens-2", "preta", "Passagem", "Passagem de guarda 2"),
    Requirement("preta-passagens-3", "preta", "Passagem", "Passagem de guarda 3"),
    Requirement("preta-passagens-4", "preta", "Passagem", "Passagem de guarda 4"),
    Requirement("preta-passagens-5", "preta", "Passagem", "Passagem da meia guarda"),
    Requirement("preta-passagens-6", "preta", "Passagem", "Passagem da guarda 50/50"),
    Requirement("preta-passagens-7", "preta", "Passagem", "Passagem da guarda de lapela"),
    Requirement("preta-armlocks-1", "preta", "Finalizações", "Arm Lock 1"),
    Requirement("preta-armlocks-2", "preta", "Finalizações", "Arm Lock 2"),
    Requirement("preta-armlocks-3", "preta", "Finalizações", "Arm Lock 3"),
    Requirement("preta-armlocks-4", "preta", "Finalizações", "Arm Lock 4"),
    Requirement("preta-triangulos-1", "preta", "Finalizações", "Triângulo 1"),
    Requirement("preta-triangulos-2", "preta", "Finalizações", "Triângulo 2"),
    Requirement("preta-omoplatas-1", "preta", "Finalizações", "Omoplata 1"),
    Requirement("preta-omoplatas-2", "preta", "Finalizações", "Omoplata 2"),
    Requirement("preta-final-joelho-1", "preta", "Finalizações", "Finalização com joelho na barriga 1"),
    Requirement("preta-final-joelho-2", "preta", "Finalizações", "Finalização com joelho na barriga 2"),
    Requirement("preta-final-joelho-3", "preta", "Finalizações", "Finalização com joelho na barriga 3"),
    Requirement("preta-final-costas-1", "preta", "Finalizações", "Finalização nas costas 1"),
    Requirement("preta-final-costas-2", "preta", "Finalizações", "Finalização nas costas 2"),
    Requirement("preta-final-costas-3", "preta", "Finalizações", "Finalização nas costas 3"),
    Requirement("preta-final-costas-4", "preta", "Finalizações", "Finalização nas costas 4"),
    Requirement("preta-final-5050", "preta", "Finalizações", "Finalização da guarda 50/50"),
    Requirement("preta-final-pe-1", "preta", "Finalizações", "Finalização no pé 1"),
    Requirement("preta-final-pe-2", "preta", "Finalizações", "Finalização no pé 2"),
    Requirement("preta-final-pe-3", "preta", "Finalizações", "Finalização no pé 3"),
    Requirement("preta-leglock-1", "preta", "Finalizações", "Leg Lock 1"),
    Requirement("preta-leglock-2", "preta", "Finalizações", "Leg Lock 2"),
    Requirement("preta-estrang-100kg-1", "preta", "Finalizações", "Estrangulamento no 100kg 1"),
    Requirement("preta-estrang-100kg-2", "preta", "Finalizações", "Estrangulamento no 100kg 2"),
    Requirement("preta-estrang-100kg-3", "preta", "Finalizações", "Estrangulamento no 100kg 3"),
    Requirement("preta-saidas-1", "preta", "Saídas", "Saída da montada 1"),
    Requirement("preta-saidas-2", "preta", "Saídas", "Saída da montada 2"),
    Requirement("preta-saidas-3", "preta", "Saídas", "Saída da montada 3"),
    Requirement("preta-costas-1", "preta", "Costas", "Ida para as costas - Berimbolo"),
    Requirement("preta-costas-2", "preta", "Costas", "Ida para as costas 2"),
    Requirement("preta-costas-3", "preta", "Costas", "Ida para as costas 3"),
)

fun requirementsByBelt(beltId: String) = ALL_REQUIREMENTS.filter { it.belt == beltId }

fun requirementsByBeltGrouped(beltId: String): Map<String, List<Requirement>> =
    requirementsByBelt(beltId).groupBy { it.category }
